import type { Metadata } from "next";
import {Titillium_Web} from "next/font/google";
import "./globals.css";
import "bootstrap-italia/dist/css/bootstrap-italia.min.css";
import Navbar from "@/app/(routes)/navbar/page";
import {AuthContextProvider} from "@/lib/authContext";
const Titillium = Titillium_Web({weight:"400",subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={Titillium.className} suppressHydrationWarning>
      <AuthContextProvider>
      <Navbar/>
      {children}
      </AuthContextProvider>
      </body>
    </html>
  );
}
